export {default as abouts} from './abouts'
export {default as brands} from './brands'
export {default as concat} from './contact'
export {default as experiences} from './experiences'
export {default as skills} from './skills'
export {default as testimonials} from './testimonials'
export {default as workExperience} from './workExperience'
export {default as works} from './works'
